org: samvabi
app: stocks-serverless-pipeline
service: stocks-serverless-pipeline

provider:
  name: aws
  runtime: python3.12
  environment:
    MOVERS_TABLE: stock-movers-${sls:stage}

functions:
  hello:
    handler: backend/handlers/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    MoversTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stock-movers-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH


