org: samvabi
app: stocks-serverless-pipeline
service: stocks-serverless-pipeline

provider:
  name: aws
  runtime: python3.12

  environment:
    STOCK_API_KEY: ${env:STOCK_API_KEY}
    MOVERS_TABLE: stock-movers-${sls:stage}
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/stock-movers-${sls:stage}

custom:
  pythonRequirements:
    fileName: backend/requirements.txt

functions:
  ingest:
    handler: backend/handlers/ingest.handler
    timeout: 30
    events:
      - schedule:
          rate: cron(15 0 ? * TUE-SAT *)
          enabled: true

  retrieve:
    handler: backend/handlers/retrieve.handler
    events:
      - httpApi:
          path: /movers
          method: get

resources:
  Resources:
    MoversTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stock-movers-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
